# Form implementation generated from reading ui file 'designer\form.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(566, 386)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.wordlistComboBox = QtWidgets.QComboBox(Dialog)
        self.wordlistComboBox.setObjectName("wordlistComboBox")
        self.gridLayout.addWidget(self.wordlistComboBox, 0, 1, 1, 1)
        self.startLabel = QtWidgets.QLabel(Dialog)
        self.startLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.startLabel.setObjectName("startLabel")
        self.gridLayout.addWidget(self.startLabel, 1, 1, 1, 1)
        self.endLabel = QtWidgets.QLabel(Dialog)
        self.endLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.endLabel.setObjectName("endLabel")
        self.gridLayout.addWidget(self.endLabel, 1, 2, 1, 1)
        self.lengthSpinBox = QtWidgets.QSpinBox(Dialog)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.gridLayout.addWidget(self.lengthSpinBox, 2, 0, 1, 1)
        self.startSpinBox = QtWidgets.QSpinBox(Dialog)
        self.startSpinBox.setObjectName("startSpinBox")
        self.gridLayout.addWidget(self.startSpinBox, 2, 1, 1, 1)
        self.listLength = QtWidgets.QLabel(Dialog)
        self.listLength.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.listLength.setObjectName("listLength")
        self.gridLayout.addWidget(self.listLength, 1, 0, 1, 1)
        self.endSpinBox = QtWidgets.QSpinBox(Dialog)
        self.endSpinBox.setObjectName("endSpinBox")
        self.gridLayout.addWidget(self.endSpinBox, 2, 2, 1, 1)
        self.generatedList = QtWidgets.QListWidget(Dialog)
        self.generatedList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.generatedList.setObjectName("generatedList")
        self.gridLayout.addWidget(self.generatedList, 4, 0, 1, 3)
        self.wordlistLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wordlistLabel.setFont(font)
        self.wordlistLabel.setObjectName("wordlistLabel")
        self.gridLayout.addWidget(self.wordlistLabel, 0, 0, 1, 1)
        self.generateButton = QtWidgets.QPushButton(Dialog)
        self.generateButton.setDefault(True)
        self.generateButton.setObjectName("generateButton")
        self.gridLayout.addWidget(self.generateButton, 3, 1, 1, 1)
        self.copyButton = QtWidgets.QPushButton(Dialog)
        self.copyButton.setObjectName("copyButton")
        self.gridLayout.addWidget(self.copyButton, 5, 2, 1, 1)
        self.wordCountLabel = QtWidgets.QLabel(Dialog)
        self.wordCountLabel.setObjectName("wordCountLabel")
        self.gridLayout.addWidget(self.wordCountLabel, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Random Word Generator"))
        self.startLabel.setText(_translate("Dialog", "Start"))
        self.endLabel.setText(_translate("Dialog", "End"))
        self.listLength.setText(_translate("Dialog", "Length"))
        self.wordlistLabel.setText(_translate("Dialog", "Wordlist:"))
        self.generateButton.setText(_translate("Dialog", "Generate"))
        self.copyButton.setText(_translate("Dialog", "Copy"))
        self.wordCountLabel.setText(_translate("Dialog", "Word Count:"))
